/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.MainScene {
    export class MainSceneUI extends Scene {
		public DepBtn:Laya.Button;
		public UsageBtn:Laya.Button;
		public AreaBtn:Laya.Button;
		public MultiBtn:Laya.Button;
		public _2D3DBtn:Laya.Button;
		public AllBtn:Laya.Button;
		public DistributeBtn:Laya.Button;
        public static  uiView:any ={"type":"Scene","props":{"width":600,"height":900},"compId":2,"child":[{"type":"Button","props":{"y":271,"x":23,"width":80,"var":"DepBtn","skin":"comp/button.png","labelSize":30,"label":"科室","height":60},"compId":7},{"type":"Button","props":{"y":355,"x":23,"width":80,"var":"UsageBtn","skin":"comp/button.png","labelSize":30,"label":"用途","height":60},"compId":8},{"type":"Button","props":{"y":437,"x":23,"width":80,"var":"AreaBtn","skin":"comp/button.png","labelSize":30,"label":"面积","height":60},"compId":9},{"type":"Button","props":{"y":600,"x":476,"width":80,"var":"MultiBtn","skin":"comp/button.png","labelSize":30,"label":"折叠","height":60},"compId":13},{"type":"Button","props":{"y":680,"x":23,"width":80,"var":"_2D3DBtn","skin":"comp/button.png","labelSize":30,"label":"2D","height":60},"compId":14},{"type":"Button","props":{"y":680,"x":476,"width":80,"var":"AllBtn","skin":"comp/button.png","labelSize":30,"label":"全部","height":60},"compId":26},{"type":"Button","props":{"y":55,"x":476,"width":80,"var":"DistributeBtn","skin":"comp/button.png","labelSize":30,"label":"分布","height":60},"compId":98}],"loadList":["comp/button.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(MainSceneUI.uiView);
        }
    }
    REG("ui.MainScene.MainSceneUI",MainSceneUI);
}
export module ui.portal {
    export class LoadingUI extends Scene {
		public Background:Laya.Image;
		public Title:Laya.Label;
		public LoginBtn:Laya.Button;
		public ProgressBar:Laya.ProgressBar;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("portal/Loading");
        }
    }
    REG("ui.portal.LoadingUI",LoadingUI);
}